- name: Install mariadb and dependencies
  ansible.builtin.apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present
    update_cache: true

- name: Enable mariadb server
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Removes anonymous user
  community.mysql.mysql_user:
    name: ''
    column_case_sensitive: false
    host: localhost
    state: absent
    login_unix_socket: /run/mysqld/mysqld.sock
