- name: Install required packages
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - gnupg
    state: present
    update_cache: true

- name: Create directory for GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker key
  ansible.builtin.get_url:
    url: 'https://download.docker.com/linux/debian/gpg'
    dest: /etc/apt/keyrings/docker.asc
    mode: '0600'

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present
    filename: docker

- name: Install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Configure Docker daemon options
  ansible.builtin.template:
    src: "templates/docker_daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: 'root'
    group: 'root'
    mode: '0755'
  notify: Restart Docker

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
