---
- name: Update pihole
  community.docker.docker_container_exec:
    container: pihole
    command: pihole -up
  notify: Update gravity

- name: Update gravity
  community.docker.docker_container_exec:
    container: pihole
    command: pihole -g
