---
- name: Docker compose up changed
  block:
    - name: Update Pi-hole
      community.docker.docker_container_exec:
        container: pihole
        command: pihole -up
    - name: Update gravity (adlists)
      community.docker.docker_container_exec:
        container: pihole
        command: pihole -g
