- name: Base setup
  hosts: all
  become: yes
  tasks:
    - name: update system
      apt:
        update_cache: yes
        upgrade: no

    - name: install base packages
      apt:
        name:
        - sudo
        - curl
        - wget
        - git
        - tcpdump
        - vim
        - htop

    - name: Create 'kamil' group
      group:
        name: kamil
        state: present

    - name: Create 'kamil' user
      user:
        name: kamil
        groups: kamil
        shell: /bin/bash
        state: present

    - name: Add public key
      authorized_key:
        user: kamil
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJF3mRlmUdCwWujN49vBX6n1cmp1CwEtqsYZf8eUftzt kamil@thinkpad"

    - name: add 'kamil' to sudoers file
      copy:
        src: ../files/sudoer_kamil
        dest: /etc/sudoers.d/kamil
        owner: root
        group: root
        mode: 0440
