- name: Install BIND9
  ansible.builtin.apt:
    name:
      - bind9
      - bind9utils
      - dnsutils
    state: present
    update_cache: true

- name: Create DNS zones directory
  ansible.builtin.file:
    path: /etc/bind/zones
    state: directory
    owner: bind
    group: bind
    mode: "0755"

- name: Configure named.conf
  ansible.builtin.template:
    src: named.conf.j2
    dest: /etc/bind/named.conf
    owner: bind
    group: bind
    mode: "0640"
  notify: Restart BIND9

- name: Configure zone in named.conf.local
  ansible.builtin.blockinfile:
    path: /etc/bind/named.conf.local
    block: |
      zone "{{ zone_name }}" {
          type master;
          file "/etc/bind/zones/db.{{ zone_name }}";
      };
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ zone_name }}"
    owner: bind
    group: bind
    mode: "0640"
    create: true
  notify: Restart BIND9

- name: Deploy zone file
  ansible.builtin.template:
    src: db.zone.j2
    dest: /etc/bind/zones/db.{{ zone_name }}
    owner: bind
    group: bind
    mode: '0644'
  notify: Restart BIND9

- name: Enable and start BIND9 service
  ansible.builtin.service:
    name: bind9
    state: started
    enabled: true
