- name: Create directory structure for Nextcloud
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  loop:
    - /home/{{ ansible_user }}/nextcloud/
    - /home/{{ ansible_user }}/nextcloud/data/
    - /home/{{ ansible_user }}/nextcloud/database/

- name: Deploy nextcloud with docker-compose
  ansible.builtin.template:
    src: "docker-compose.yaml.j2"
    dest: "/home/{{ ansible_user }}/nextcloud/docker-compose.yaml"
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Run docker compose
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/nextcloud
    state: present
    pull: always
