- name: Setup Pi-hole directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  loop:
    - /home/{{ ansible_user }}/pihole/
    - /home/{{ ansible_user }}/pihole/data
    - /home/{{ ansible_user }}/pihole/data/etc-pihole

- name: Disable systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Deploy pihole with docker-compose
  ansible.builtin.template:
    src: "docker-compose.yaml.j2"
    dest: "/home/{{ ansible_user }}/pihole/docker-compose.yaml"
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

# Don't work yet
- name: Copy adlist.list
  ansible.builtin.template:
    src: "adlist.list.j2"
    dest: "/home/{{ ansible_user }}/pihole/data/etc-pihole/adlist.list"
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Run pihole docker compose
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_user }}/pihole
    state: present
    pull: always
    recreate: auto
    remove_orphans: true

- name: Update Pi-hole
  community.docker.docker_container_exec:
    container: pihole
    command: pihole -up
    detach: false

- name: Update gravity (adlists)
  community.docker.docker_container_exec:
    container: pihole
    command: pihole -g
    detach: false
