debian:
  vars:
    ansible_user: 'kamil'
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    docker-host-101:
      ansible_host: 172.30.20.101
    nextcloud-102:
      ansible_host: 172.30.20.102

docker:
  vars:
    ansible_user: 'kamil'
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    docker-host-101:
      ansible_host: 172.30.20.101
