---
- name: Hardening servers
  hosts: all
  become: true
  roles:
    - hardening

- name: Deploy docker
  hosts: docker_hosts
  become: true
  roles:
    - docker-install

- name: Deploy Pi-hole servers
  hosts: pihole
  become: true
  roles:
    - pihole-deployment

- name: Deploy bind9 servers
  hosts: bind9
  become: true
  roles:
    - bind9-deployment

- name: Deploy traefik proxy
  hosts: docker-host
  become: true
  roles:
    - traefik-proxy

- name: Deploy mariadb
  hosts: mysql
  become: true
  roles:
    - mariadb

- name: Deploy nextcloud
  hosts: nextcloud
  become: true
  roles:
    - nextcloud

- name: Deploy monitoring stack
  hosts: docker-host
  become: true
  roles:
    - monitoring
