---
- name: Deploy Pi-hole servers
  hosts: pihole
  become: true
  roles:
    - docker-install
    - pihole-deployment

- name: Deploy bind9 servers
  hosts: bind9
  become: true
  roles:
    - bind9-deployment
