---
- name: Setting up servers
  hosts: all
  become: true
  roles:
    - hardening
    - initial-setup

- name: Deploy docker
  hosts: docker_hosts
  become: true
  roles:
    - docker-install

- name: Deploy Pi-hole servers
  hosts: pihole
  become: true
  roles:
    - pihole-deployment

- name: Deploy bind9 servers
  hosts: bind9
  become: true
  roles:
    - bind9-deployment

- name: Deploy docker-host VM
  hosts: docker-host
  become: true
  roles:
    - traefik-proxy
    - monitoring-server
    - monitoring-node
    - notes

- name: Deploy nextcloud
  hosts: nextcloud
  become: true
  roles:
    - nextcloud
    - monitoring-node
